apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
  namespace: dev-environment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
        - name: neo4j
          image: neo4j:latest
          ports:
            - containerPort: 7474
            - containerPort: 7687
          env:
            - name: NEO4J_AUTH
              value: neo4j/test
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: dev-environment
spec:
  ports:
    - port: 7474
      targetPort: 7474
    - port: 7687
      targetPort: 7687
  selector:
    app: neo4j
